// Re-export shared domain types from @wim/types so existing imports keep working.
// New code should import directly from "@wim/types".
export type {
  AlertItem,
  AlertKind,
  AlertStatus,
  Article,
  ArticleListParams,
  ArticleListResult,
  ArticleNote,
  ArticleNoteKind,
  ArticleWarranty,
  AttachmentItem,
  AttachmentType,
  BillingSubscription,
  ClaimStatus,
  DashboardStatistics,
  FetchedArticle,
  Location,
  MonthlyBucket,
  SavedView,
  ShareInviteItem,
  ShareItem,
  SharedArticleRow,
  Tag,
  WarrantyItem,
} from "@wim/types";
